### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by rishabhdoshi09** [gnotaras/wordpress-add-headers#1]
something is wrong with the header encoding and with not adding the ET codes- how do I add, like exactly how?

**Comment by gnotaras** [comment]
Hello,

I'm going to need some details before I'll be able to help you, because I'm a little confused about what exactly is the problem. Are you referring to the _ETag_ header?

Encoding related information is usually set in the _Content-Type_ header, which is not handled by _Add-Headers_.

Please be more specific so I can help you.

Kind Regards,
George

**Comment by akashk92** [comment]
I installed this plugin but it still doesn't add expires and cache-control on static files likes images..
In response Headers I Am not getting any expires headers

**Comment by gnotaras** [comment]
> [...] but it still doesn't add expires and cache-control on static files likes images..

Hi, the plugin adds the HTTP headers only to responses generated by WordPress. This includes all dynamic pages, but not static files like images, css or javascript. The responses for those files are actually generated by the web server and WordPress has no involvement, and thus Add-Headers could not process the HTTP headers for those resources.

However, you will find plenty of tutorials on the web about how to configure the web server (.htaccess included) so as to add all these headers in the HTTP responses for static files.

If you need more help, please let me know.

George

**Comment by gnotaras** [comment]
For an in depth explanation and info, you can check [this guide](http://www.askapache.com/htaccess/speed-up-sites-with-htaccess-caching.html).

**Comment by gnotaras** [comment]
Akash, I'm going to close this issue as it's rather old and the original poster hasn't provided any more feedback. However, if you need more help, please feel free to open a new issue.

Kind Regards,
George
